language: csharp
sudo: false
dist: trusty
mono: none
dotnet: 2.1.4
os: linux
before_install:
  - git fetch --unshallow
  - choco install GitVersion.Portable
script:
  - dotnet restore
  - dotnet build -c Release
  
deploy:
    skip_cleanup: true
    provider: script
    script: sh ./deploy.bat
