language: csharp
sudo: false
dist: trusty
mono: none
dotnet: 2.1.4
os: linux

script:
  - dotnet restore
  - dotnet build -c Release --no-restore
  
before_deploy: 
  
deploy:
    skip_cleanup: true
    provider: script
    script: sh ./deploy.sh 2.0.0 $MYGET_SOURCE $MYGET_APIKEY
