language: csharp
sudo: false
dist: trusty
mono: none
dotnet: 2.1.4
os: linux

script:
  - dotnet restore
  - dotnet build -c Release
  
deploy:
    skip_cleanup: true
    provider: script
    script: sh ./deploy.sh 1.0.0-CI%TRAVIS_BUILD_NUMBER%
